import React, { useEffect, useState } from "react";
import { api, MediaAsset } from "../api";

export default function Files() {
  const [assets, setAssets] = useState<MediaAsset[]>([]);
  const [filter, setFilter] = useState("");

  useEffect(() => {
    api.assets().then(setAssets).catch(() => {});
  }, []);

  const kinds = Array.from(new Set(assets.map((a) => a.kind || "unknown")));
  const filtered = filter ? assets.filter((a) => (a.kind || "unknown") === filter) : assets;

  return (
    <div className="t-page">
      <div className="t-page-inner">
        <div className="mb-6">
          <div className="t-heading">Files</div>
          <div className="t-sub">
            Artifacts generated by your agents — images, videos, and documents created during execution.
          </div>
        </div>

        {kinds.length > 1 && (
          <div className="mb-5 flex flex-wrap gap-2">
            <button
              onClick={() => setFilter("")}
              className={`t-chip ${!filter ? "border-accent/60 text-text-primary" : ""}`}
            >
              All · {assets.length}
            </button>
            {kinds.map((k) => (
              <button
                key={k}
                onClick={() => setFilter(k)}
                className={`t-chip ${filter === k ? "border-accent/60 text-text-primary" : ""}`}
              >
                {k} · {assets.filter((a) => (a.kind || "unknown") === k).length}
              </button>
            ))}
          </div>
        )}

        {filtered.length === 0 ? (
          <div className="flex flex-col items-center gap-3 rounded-xl border border-border bg-bg-secondary py-16 text-center">
            <div className="text-2xl text-text-muted">▤</div>
            <div className="text-sm font-medium text-text-secondary">No files yet</div>
            <div className="text-[13px] text-text-muted">Artifacts your agents produce will appear here.</div>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {filtered.map((a) => (
              <a
                key={a.id}
                href={a.url}
                target="_blank"
                rel="noreferrer"
                className="group overflow-hidden rounded-xl border border-border bg-bg-secondary transition hover:border-border-hover"
              >
                {a.kind === "video" ? (
                  <video src={a.url} className="h-32 w-full object-cover" muted playsInline />
                ) : (
                  <div className="grid h-32 w-full place-items-center bg-bg-tertiary text-2xl text-text-muted">
                    {a.url && !a.url.endsWith(".mp4") ? <span>🖼</span> : <span>▤</span>}
                  </div>
                )}
                <div className="border-t border-border p-2.5">
                  <div className="truncate text-[12px] text-text-secondary">{a.title || a.prompt || "Artifact"}</div>
                  <div className="mt-0.5 text-[10.5px] text-text-muted">
                    {a.kind} · {a.creator_agent || "agent"}
                  </div>
                </div>
              </a>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
